// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3LYUMXagIPhygVxBHuI3aQtGaY5xMmMQ',
    appId: '1:209384219289:web:65f2d816704c1c64094e08',
    messagingSenderId: '209384219289',
    projectId: 'unigo2-c8efd',
    authDomain: 'unigo2-c8efd.firebaseapp.com',
    storageBucket: 'unigo2-c8efd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhyIB4J3N2lZRZi0E9JGoUM1Snu-nx5GM',
    appId: '1:209384219289:android:81bb6a7d05470e58094e08',
    messagingSenderId: '209384219289',
    projectId: 'unigo2-c8efd',
    storageBucket: 'unigo2-c8efd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt66EClE_FhBrXb8LgZiVf9Qay18yKFNk',
    appId: '1:209384219289:ios:0656bc2f0b90d732094e08',
    messagingSenderId: '209384219289',
    projectId: 'unigo2-c8efd',
    storageBucket: 'unigo2-c8efd.firebasestorage.app',
    iosBundleId: 'com.example.flutterUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt66EClE_FhBrXb8LgZiVf9Qay18yKFNk',
    appId: '1:209384219289:ios:0656bc2f0b90d732094e08',
    messagingSenderId: '209384219289',
    projectId: 'unigo2-c8efd',
    storageBucket: 'unigo2-c8efd.firebasestorage.app',
    iosBundleId: 'com.example.flutterUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3LYUMXagIPhygVxBHuI3aQtGaY5xMmMQ',
    appId: '1:209384219289:web:a44f2a83c3cceb04094e08',
    messagingSenderId: '209384219289',
    projectId: 'unigo2-c8efd',
    authDomain: 'unigo2-c8efd.firebaseapp.com',
    storageBucket: 'unigo2-c8efd.firebasestorage.app',
  );
}
